API 2.0 schema re-work
kubeportal/kubeportal pull request #138
Opened 2021-02-20 16:17 UTC by troeger

This is an attempted fix for #135, which introduces unique keys in all dictionaries used the API. The intention here is to simplify the mapping to input forms in the new frontend.

2021-02-21 12:09 UTC, DenizCankurtaran reviewed
It feels much cleaner, thank you!

2021-02-22 08:37 UTC, kat-hi requested changes

2021-02-22 08:37 UTC, kat-hi commented on kubeportal/k8s/kubernetes_api.py
> +        metadata=client.V1ObjectMeta(name=tpl['name'], labels=k8s_labels),
pls rnm tpl

2021-02-22 09:53 UTC, merged

2021-02-22 09:53 UTC, troeger commented on kubeportal/k8s/kubernetes_api.py
> +        metadata=client.V1ObjectMeta(name=tpl['name'], labels=k8s_labels),
fxd

2021-02-22 10:26 UTC, DenizCankurtaran commented on kubeportal/k8s/kubernetes_api.py
> +        metadata=client.V1ObjectMeta(name=tpl['name'], labels=k8s_labels),
btfl